export const categories=[
    {
        id:1,
        Title:'Education',
        icon:require('../Assets/icons8-education-30.png'),
        color:'blue'
    },
    {
        id:2,
        Title:'Entertainment',
        icon:require('../Assets/icons8-battle.net-50(1).png'),
        color:'red'
    },
    {
        id:3,
        Title:'Food',
        icon:require('../Assets/icons8-food-and-wine-50.png'),
        color:'purple'
    },
    {
        id:4,
        Title:'Healthcare',
        icon:require('../Assets/icons8-doctors-bag-50.png'),
        color:'green'
    },
    {
        id:5,
        Title:'Shopping',
        icon:require('../Assets/icons8-buying-50.png'),
        color:'yellow'
    }
]